import random
import matplotlib.pyplot as plt
import time


def devlog():
    print(register)
    print(len(register))

    wlen = [0 for i in range(11)]
    for word in register:
        for i in range(6):
            if len(word) == i+6:
                wlen[i+5] += 1

    for i in range(6):
        print(f"{i+5} letter words: {wlen[i+5]}")

    chars = 0
    for i in range(6):
        chars += (5+i)*int(2**(n-i-1))
    print(f"Total no. of characters: {chars}")

    plt.plot(wlen)
    plt.xlabel("Length of the words")
    plt.ylabel("Number of words")
    plt.show()

def newline():
    print("_"*100+"\n")

words = [[],[],[],[],[],[]]

words[0] = [
'About', 'Alert', 'Argue', 'Beach', 'Above', 'Alike', 'Arise', 'Began', 'Abuse', 'Alive', 'Array', 'Begin', 'Actor', 'Allow', 'Aside', 'Begun', 'Acute', 'Alone', 'Asset', 'Being', 'Admit', 'Along', 'Audio', 'Below', 'Adopt', 'Alter', 'Audit', 'Bench', 'Adult', 'Among', 'Avoid', 'Billy', 'After', 'Anger', 'Award', 'Birth', 'Again', 'Angle', 'Aware', 'Black', 'Agent', 'Angry', 'Badly', 'Blame', 'Agree', 'Apart', 'Baker', 'Blind', 'Ahead', 'Apple', 'Bases', 'Block', 'Alarm', 'Apply', 'Basic', 'Blood', 'Album', 'Arena', 'Basis', 'Board', 'Boost', 'Buyer', 'China', 'Cover', 'Booth', 'Cable', 'Chose', 'Craft', 'Bound', 'Calif', 'Civil', 'Crash', 'Brain', 'Carry', 'Claim', 'Cream', 'Brand', 'Catch', 'Class', 'Crime', 'Bread', 'Cause', 'Clean', 'Cross', 'Break', 'Chain', 'Clear', 'Crowd', 'Breed', 'Chair', 'Click', 'Crown', 'Brief', 'Chart', 'Clock', 'Curve', 'Bring', 'Chase', 'Close', 'Cycle', 'Broad', 'Cheap', 'Coach', 'Daily', 'Broke', 'Check', 'Coast', 
'Dance', 'Brown', 'Chest', 'Could', 'Dated', 'Build', 'Chief', 'Count', 'Dealt', 'Built', 'Child', 'Court', 'Death', 'Debut', 'Entry', 'Forth', 'Group', 'Delay', 'Equal', 'Forty', 'Grown', 'Depth', 'Error', 'Forum', 'Guard', 'Doing', 'Event', 'Found', 'Guess', 'Doubt', 'Every', 'Frame', 'Guest', 'Dozen', 'Exact', 'Frank', 'Guide', 'Draft', 'Exist', 'Fraud', 'Happy', 'Drama', 'Extra', 'Fresh', 'Harry', 'Drawn', 'Faith', 'Front', 'Heart', 'Dream', 'False', 'Fruit', 'Heavy', 'Dress', 'Fault', 'Fully', 'Hence', 'Drill', 'Fiber', 'Funny', 'Henry', 'Drink', 'Field', 'Giant', 'Horse', 'Drive', 'Fifth', 'Given', 'Hotel', 'Drove', 'Fifty', 'Glass', 'House', 'Dying', 'Fight', 'Globe', 'Human', 'Eager', 'Final', 'Going', 'Ideal', 'Early', 'First', 'Grace', 'Image', 'Earth', 'Fixed', 'Grade', 'Index', 'Eight', 'Flash', 'Grand', 'Inner', 'Elite', 'Fleet', 'Grant', 'Input', 'Empty', 'Floor', 'Grass', 'Issue', 'Enemy', 'Fluid', 'Great', 'Irony', 'Enjoy', 'Focus', 'Green', 'Juice', 'Enter', 'Force', 'Gross', 'Joint', 'Jones', 'Links', 'Media', 'Newly', 'Judge', 'Lives', 'Metal', 'Night', 
'Known', 'Local', 'Might', 'Noise', 'Label', 'Logic', 'Minor', 'North', 'Large', 'Loose', 'Minus', 'Noted', 'Laser', 'Lower', 'Mixed', 'Novel', 'Later', 'Lucky', 'Model', 'Nurse', 'Laugh', 'Lunch', 'Money', 'Occur', 'Layer', 'Lying', 'Month', 'Ocean', 'Learn', 'Magic', 'Moral', 'Offer', 'Lease', 'Major', 'Motor', 'Often', 'Least', 'Maker', 'Mount', 'Order', 'Leave', 'March', 'Mouse', 'Other', 'Legal', 'Maria', 'Mouth', 'Ought', 'Level', 'Match', 'Movie', 'Paint', 'Lewis', 'Maybe', 'Music', 'Panel', 'Light', 'Mayor', 'Needs', 'Paper', 'Limit', 'Meant', 'Never', 'Party', 'Peace', 'Power', 'Radio', 'Round', 'Peter', 'Press', 'Raise', 'Route', 'Phase', 'Price', 'Range', 'Royal', 'Phone', 'Pride', 'Rapid', 'Rural', 'Photo', 'Prime', 'Ratio', 'Scale', 'Piece', 'Print', 'Reach', 'Scene', 'Pilot', 'Prior', 'Ready', 'Scope', 'Pitch', 'Prize', 'Refer', 'Score', 'Place', 'Proof', 'Right', 'Sense', 'Plain', 'Proud', 'Rival', 'Serve', 'Plane', 'Prove', 'River', 'Seven', 'Plant', 'Queen', 'Robin', 'Shall', 'Plate', 'Quick', 'Roger', 'Shape', 'Point', 'Quiet', 'Roman', 'Share', 'Pound', 
'Quite', 'Rough', 'Sharp', 'Sheet', 'Spare', 'Style', 'Times', 'Shelf', 'Speak', 'Sugar', 'Tired', 'Shell', 'Speed', 'Suite', 'Title', 'Shift', 'Spend', 'Super', 'Today', 'Shirt', 'Spent', 'Sweet', 'Topic', 'Shock', 'Split', 'Table', 'Total', 'Shoot', 'Spoke', 'Taken', 'Touch', 'Short', 'Sport', 'Taste', 'Tough', 'Shown', 'Staff', 'Taxes', 'Tower', 'Sight', 'Stage', 'Teach', 'Track', 'Since', 'Stake', 'Teeth', 'Trade', 'Sixth', 'Stand', 'Terry', 'Train', 'Sixty', 'Start', 'Texas', 'Treat', 'Sized', 'State', 'Thank', 'Trend', 'Skill', 'Steam', 'Theft', 'Trial', 'Sleep', 'Steel', 'Their', 'Tried', 'Slide', 'Stick', 'Theme', 'Tries', 'Small', 'Still', 'There', 'Truck', 'Smart', 'Stock', 'These', 'Truly', 'Smile', 'Stone', 'Thick', 'Trust', 'Smith', 'Stood', 'Thing', 'Truth', 'Smoke', 'Store', 'Think', 'Twice', 'Solid', 'Storm', 'Third', 'Under', 'Solve', 'Story', 'Those', 'Undue', 'Sorry', 'Strip', 'Three', 'Union', 'Sound', 'Stuck', 'Threw', 'Unity', 'South', 'Study', 'Throw', 'Until', 'Space', 'Stuff', 'Tight', 'Upper', 'Upset', 'Whole', 'Waste', 'Wound', 'Urban', 'Whose', 
'Watch', 'Write', 'Usage', 'Woman', 'Water', 'Wrong', 'Words', 'Usual', 'Women', 'Wheel', 'Wrote', 'Valid', 'World', 'Where', 'Yield', 'Value', 'Worry', 'Which', 'Young', 'Video', 'Worse', 'While', 'Youth', 'Virus', 'Worst', 'White', 'Worth', 'Visit', 'Would', 'Vital'
]

words[1] = [
'Better', 'Beyond', 'Bishop', 'Border', 'Bottle', 'Bottom', 'Bought', 'Branch', 'Breath', 'Bridge', 'Bright', 'Broken', 'Budget', 'Burden', 'Bureau', 'Button', 'Camera', 'Cancer', 'Cannot', 'Carbon', 'Career', 'Castle', 'Casual', 'Caught', 'Center', 'Centre', 'Chance', 'Change', 'Charge', 'Choice', 'Choose', 'Chosen', 'Church', 'Circle', 'Client', 'Closed', 'Closer', 'Coffee', 'Column', 'Combat', 'Coming', 'Common', 'Comply', 'Copper', 'Corner', 'Costly', 'County', 'Couple', 'Course', 'Covers', 'Create', 'Credit', 'Crisis', 'Custom', 'Damage', 'Danger', 'Dealer', 'Debate', 'Decade', 'Decide', 
'Defeat', 'Defend', 'Define', 'Degree', 'Demand', 'Depend', 'Deputy', 'Desert', 'Design', 'Desire', 'Detail', 'Detect', 'Device', 'Differ', 'Dinner', 'Direct', 'Doctor', 'Dollar', 'Domain', 'Double', 'Driven', 'Driver', 'During', 'Easily', 'Eating', 'Editor', 'Effect', 'Effort', 'Eighth', 'Either', 'Eleven', 'Emerge', 'Empire', 'Employ', 'Enable', 'Ending', 'Energy', 'Engage', 'Engine', 'Enough', 'Ensure', 'Entire', 'Entity', 'Equity', 'Escape', 'Estate', 'Ethnic', 'Exceed', 'Except', 'Excess', 'Expand', 'Expect', 'Expert', 'Export', 'Extend', 'Extent', 'Fabric', 'Facing', 'Factor', 'Failed', 'Fairly', 'Fallen', 'Family', 'Famous', 'Father', 'Fellow', 'Female', 'Figure', 'Filing', 'Finger', 'Finish', 'Fiscal', 'Flight', 'Flying', 'Follow', 'Forced', 'Forest', 'Forget', 'Formal', 'Format', 'Former', 'Foster', 'Fought', 'Fourth', 'French', 'Friend', 'Future', 'Garden', 'Gather', 'Gender', 'German', 'Global', 'Golden', 'Ground', 'Growth', 'Guilty', 'Handed', 'Handle', 'Happen', 'Hardly', 'Headed', 'Health', 'Height', 'Hidden', 'Holder', 'Honest', 'Impact', 'Import', 'Income', 'Indeed', 'Injury', 'Inside', 'Intend', 'Intent', 'Invest', 'Island', 'Itself', 'Jersey', 'Joseph', 'Junior', 'Killed', 
'Labour', 'Latest', 'Latter', 'Launch', 'Lawyer', 'Leader', 'League', 'Leaves', 'Legacy', 'Length', 'Lesson', 'Letter', 'Lights', 'Likely', 'Linked', 'Liquid', 'Listen', 'Little', 'Living', 'Losing', 'Lucent', 'Luxury', 'Mainly', 'Making', 'Manage', 'Manner', 'Manual', 'Margin', 'Marine', 'Marked', 'Market', 'Martin', 'Master', 'Matter', 'Mature', 'Medium', 'Member', 'Memory', 'Mental', 'Merely', 'Merger', 'Method', 'Middle', 'Miller', 'Mining', 'Minute', 'Mirror', 'Mobile', 'Modern', 'Modest', 'Module', 'Moment', 'Morris', 'Mostly', 'Mother', 'Motion', 'Moving', 'Murder', 'Museum', 'Mutual', 'Myself', 'Narrow', 'Nation', 'Native', 'Nature', 'Nearby', 'Nearly', 'Nights', 'Nobody', 'Normal', 'Notice', 'Notion', 'Number', 'Object', 'Obtain', 'Office', 'Offset', 'Online', 'Option', 'Orange', 'Origin', 'Output', 'Oxford', 'Packed', 'Palace', 'Parent', 'Partly', 'Patent', 'People', 'Period', 'Permit', 'Person', 'Phrase', 'Picked', 'Planet', 'Player', 'Please', 'Plenty', 'Pocket', 'Police', 'Policy', 'Prefer', 'Pretty', 'Prince', 'Prison', 'Profit', 'Proper', 'Proven', 'Public', 'Pursue', 'Raised', 'Random', 'Rarely', 'Rather', 'Rating', 'Reader', 'Really', 'Reason', 'Recall', 'Recent', 'Record', 
'Reduce', 'Reform', 'Regard', 'Regime', 'Region', 'Relate', 'Relief', 'Remain', 'Remote', 'Remove', 'Repair', 'Repeat', 'Replay', 'Report', 'Rescue', 'Resort', 'Result', 'Retail', 'Retain', 'Return', 'Reveal', 'Review', 'Reward', 'Riding', 'Rising', 'Robust', 'Ruling', 'Safety', 'Salary', 'Sample', 'Saving', 'Saying', 'Scheme', 'School', 'Screen', 'Search', 'Season', 'Second', 'Secret', 'Sector', 'Secure', 'Seeing', 'Select', 'Seller', 'Senior', 'Series', 'Server', 'Settle', 'Severe', 'Should', 'Signal', 'Signed', 'Silent', 'Silver', 'Simple', 'Simply', 'Single', 'Sister', 'Slight', 'Smooth', 'Social', 'Solely', 'Sought', 'Source', 'Soviet', 'Speech', 'Spirit', 'Spoken', 'Spread', 'Spring', 'Square', 'Stable', 'Status', 'Steady', 'Stolen', 'Strain', 'Stream', 'Street', 'Stress', 'Strict', 'Strike', 'String', 'Strong', 'Struck', 'Studio', 'Submit', 'Sudden', 'Suffer', 'Summer', 'Summit', 'Supply', 'Surely', 'Survey', 'Switch', 'Symbol', 'System', 'Taking', 'Talent', 'Target', 'Taught', 'Tenant', 'Tender', 'Tennis', 'Thanks', 'Theory', 'Thirty', 'Though', 'Threat', 'Thrown', 'Ticket', 'Timely', 'Timing', 'Tissue', 'Toward', 'Travel', 'Treaty', 'Trying', 'Twelve', 'Twenty', 'Unable', 'Unique',
'United', 'Unless', 'Unlike', 'Update', 'Useful', 'Valley', 'Varied', 'Vendor', 'Versus', 'Victim', 'Vision', 'Visual', 'Volume', 'Walker', 'Wealth', 'Weekly', 'Weight', 'Wholly', 'Window', 'Winner', 'Winter', 'Within', 'Wonder', 'Worker', 'Wright', 'Writer', 'Yellow']

words[2] = [
'Ability', 'Absence', 'Academy', 'Account', 'Accused', 'Achieve', 'Acquire', 'Address', 'Advance', 'Adverse', 'Advised', 'Adviser', 'Against', 'Airline', 'Airport', 'Alcohol', 'Alleged', 'Already', 'Analyst', 'Ancient', 'Another', 'Anxiety', 'Anxious', 'Anybody', 'Applied', 'Arrange', 'Arrival', 'Article', 'Assault', 'Assumed', 'Assured', 'Attempt', 'Attract', 'Auction', 'Average', 'Backing', 'Balance', 'Banking', 'Barrier', 'Battery', 'Bearing', 'Beating', 'Because', 'Bedroom', 'Believe', 'Beneath', 'Benefit', 'Besides', 'Between', 'Billion', 'Binding', 'Brother', 'Brought', 'Burning', 'Cabinet', 'Caliber', 'Calling', 'Capable', 'Capital', 'Captain', 'Caption', 'Capture', 'Careful', 'Carrier', 'Caution', 'Ceiling', 'Central', 'Centric', 'Century', 'Certain', 'Chamber', 'Channel', 'Chapter', 'Charity', 'Charlie', 'Charter', 'Checked', 'Chicken', 'Chronic', 'Circuit', 'Classes', 'Classic', 'Climate', 'Closing', 'Closure', 'Clothes', 'Collect', 'College', 'Combine', 'Comfort', 'Command', 'Comment', 'Compact', 'Company', 'Compare', 'Compete', 'Complex', 'Concept', 'Concern', 'Concert', 'Conduct', 'Confirm', 'Connect', 'Consent', 'Consist', 'Contact', 'Contain', 'Content', 'Contest', 'Context',
'Control', 'Convert', 'Correct', 'Council', 'Counsel', 'Counter', 'Country', 'Crucial', 'Crystal', 'Culture', 'Current', 'Cutting', 'Dealing', 'Decided', 'Decline', 'Default', 'Defence', 'Deficit', 'Deliver', 'Density', 'Deposit', 'Desktop', 'Despite', 'Destroy', 'Develop', 'Devoted', 'Diamond', 'Digital', 'Discuss', 'Disease', 'Display', 'Dispute', 'Distant', 'Diverse', 'Divided', 'Drawing', 'Driving', 'Dynamic', 'Eastern', 'Economy', 'Edition', 'Elderly', 'Element', 'Engaged', 'Enhance', 'Essence', 'Evening', 'Evident', 'Exactly', 'Examine', 'Example', 'Excited', 'Exclude', 'Exhibit', 'Expense', 'Explain', 'Explore', 'Express', 'Extreme', 'Factory', 'Faculty', 'Failing', 'Failure', 'Fashion', 'Feature', 'Federal', 'Feeling', 'Fiction', 'Fifteen', 'Filling', 'Finance', 'Finding', 'Fishing', 'Fitness', 'Foreign', 'Forever', 'Formula', 'Fortune', 'Forward', 'Founder', 'Freedom', 'Further', 'Gallery', 'Gateway', 'General', 'Genetic', 'Genuine', 'Gigabit', 'Greater', 'Hanging', 'Heading', 'Healthy', 'Hearing', 'Heavily', 'Helpful', 'Helping', 'Herself', 'Highway', 'Himself', 'History', 'Holding', 'Holiday', 'Housing', 'However', 'Hundred', 'Husband', 'Illegal', 'Illness', 'Imagine', 'Imaging',
'Improve', 'Include', 'Initial', 'Inquiry', 'Insight', 'Install', 'Instant', 'Instead', 'Intense', 'Interim', 'Involve', 'Jointly', 'Journal', 'Journey', 'Justice', 'Justify', 'Keeping', 'Killing', 'Kingdom', 'Kitchen', 'Knowing', 'Landing', 'Largely', 'Lasting', 'Leading', 'Learned', 'Leisure', 'Liberal', 'Liberty', 'Library', 'License', 'Limited', 'Listing', 'Logical', 'Loyalty', 'Machine', 'Manager', 'Married', 'Massive', 'Maximum', 'Meaning', 'Measure', 'Medical', 'Meeting', 'Mention', 'Message', 'Million', 'Mineral', 'Minimal', 'Minimum', 'Missing', 'Mission', 'Mistake', 'Mixture', 'Monitor', 'Monthly', 'Morning', 'Musical', 'Mystery', 'Natural', 'Neither', 'Nervous', 'Network', 'Neutral', 'Notable', 'Nothing', 'Nowhere', 'Nuclear', 'Nursing', 'Obvious', 'Offense', 'Officer', 'Ongoing', 'Opening', 'Operate', 'Opinion', 'Optical', 'Organic', 'Outcome', 'Outdoor', 'Outlook', 'Outside', 'Overall', 'Pacific', 'Package', 'Painted', 'Parking', 'Partial', 'Partner', 'Passage', 'Passing', 'Passion', 'Passive', 'Patient', 'Pattern', 'Payable', 'Payment', 'Penalty', 'Pending', 'Pension', 'Percent', 'Perfect', 'Perform', 'Perhaps', 'Phoenix', 'Picking', 'Picture', 'Pioneer', 'Plastic', 'Pointed',
'Popular', 'Portion', 'Poverty', 'Precise', 'Predict', 'Premier', 'Premium', 'Prepare', 'Present', 'Prevent', 'Primary', 'Printer', 'Privacy', 'Private', 'Problem', 'Proceed', 'Process', 'Produce', 'Product', 'Profile', 'Program', 'Project', 'Promise', 'Promote', 'Protect', 'Protein', 'Protest', 'Provide', 'Publish', 'Purpose', 'Pushing', 'Qualify', 'Quality', 'Quarter', 'Radical', 'Railway', 'Readily', 'Reading', 'Reality', 'Realize', 'Receipt', 'Receive', 'Recover', 'Reflect', 'Regular', 'Related', 'Release', 'Remains', 'Removal', 'Removed', 'Replace', 'Request', 'Require', 'Reserve', 'Resolve', 'Respect', 'Respond', 'Restore', 'Retired', 'Revenue', 'Reverse', 'Rollout', 'Routine', 'Running', 'Satisfy', 'Science', 'Section', 'Segment', 'Serious', 'Service', 'Serving', 'Session', 'Setting', 'Seventh', 'Several', 'Shortly', 'Showing', 'Silence', 'Silicon', 'Similar', 'Sitting', 'Sixteen', 'Skilled', 'Smoking', 'Society', 'Somehow', 'Someone', 'Speaker', 'Special', 'Species', 'Sponsor', 'Station', 'Storage', 'Strange', 'Stretch', 'Student', 'Studied', 'Subject', 'Succeed', 'Success', 'Suggest', 'Summary', 'Support', 'Suppose', 'Supreme', 'Surface', 'Surgery', 'Surplus', 'Survive', 'Suspect',
'Sustain', 'Teacher', 'Telecom', 'Telling', 'Tension', 'Theatre', 'Therapy', 'Thereby', 'Thought', 'Through', 'Tonight', 'Totally', 'Touched', 'Towards', 'Traffic', 'Trouble', 'Turning', 'Typical', 'Uniform', 'Unknown', 'Unusual', 'Upgrade', 'Upscale', 'Utility', 'Variety', 'Various', 'Vehicle', 'Venture', 'Version', 'Veteran', 'Victory', 'Viewing', 'Village', 'Violent', 'Virtual', 'Visible', 'Waiting', 'Walking', 'Wanting', 'Warning', 'Warrant', 'Wearing', 'Weather', 'Webcast', 'Website', 'Wedding', 'Weekend', 'Welcome', 'Welfare', 'Western', 'Whereas', 'Whereby', 'Whether', 'Willing', 'Winning', 'Without', 'Witness', 'Working', 'Writing', 'Written'
]

words[3] = [
'Absolute', 'Academic', 'Accident', 'Accurate', 'Activist', 'Activity', 'Actually', 'Addition', 'Adequate', 'Advanced', 'Advocate', 'Aircraft', 'Alliance', 'Although', 'Analysis', 'Announce', 'Anything', 'Anywhere', 'Apparent', 'Approach', 'Approval', 'Argument', 'Artistic', 'Athletic', 'Attitude', 'Audience', 'Bathroom', 'Behavior', 'Birthday', 'Boundary', 'Building', 'Business', 'Campaign', 'Capacity', 'Category', 'Ceremony', 'Champion', 'Changing', 'Civilian', 'Clinical', 'Clothing', 'Collapse', 'Complain', 'Complete', 'Comprise', 'Computer', 'Conclude', 'Concrete', 'Conflict', 'Confront', 
'Confused', 'Congress', 'Consider', 'Constant', 'Consumer', 'Continue', 'Contract', 'Contrary', 'Contrast', 'Convince', 'Corridor', 'Coverage', 'Covering', 'Creation', 'Creative', 'Creature', 'Criminal', 'Criteria', 'Critical', 'Crossing', 'Cultural', 'Currency', 'Customer', 'Darkness', 'Database', 'Daughter', 'Daylight', 'Deadline', 'Deciding', 'Decision', 'Decrease', 'Deferred', 'Definite', 'Delicate', 'Delivery', 'Describe', 'Designer', 'Detailed', 'Diabetes', 'Dialogue', 'Diameter', 'Directly', 'Director', 'Disabled', 'Disagree', 'Disaster', 'Disclose', 'Discount', 'Discover', 'Disorder', 'Disposal', 'Distance', 'Distinct', 'District', 'Dividend', 'Division', 'Doctrine', 'Document', 'Domestic', 'Dominant', 'Dominate', 'Doubtful', 'Dramatic', 'Dressing', 'Dropping', 'Duration', 'Dynamics', 'Earnings', 'Economic', 'Educated', 'Educator', 'Efficacy', 'Eighteen', 'Election', 'Electric', 'Eligible', 'Emerging', 'Emission', 'Emphasis', 'Employee', 'Employer', 'Endeavor', 'Engaging', 'Engineer', 'Enormous', 'Entirely', 'Entrance', 'Envelope', 'Equality', 'Equation', 'Estimate', 'Evaluate', 'Eventual', 'Everyday', 'Everyone', 'Evidence', 'Exchange', 'Exciting', 'Exercise', 'Existing', 'Explicit',
'Exposure', 'Extended', 'External', 'Facility', 'Familiar', 'Favorite', 'Featured', 'Feedback', 'Festival', 'Fighting', 'Finished', 'Firewall', 'Flagship', 'Flexible', 'Floating', 'Football', 'Foothill', 'Forecast', 'Foremost', 'Formerly', 'Fourteen', 'Fraction', 'Franklin', 'Frequent', 'Friendly', 'Frontier', 'Function', 'Generate', 'Generous', 'Genomics', 'Goodwill', 'Governor', 'Graduate', 'Graphics', 'Grateful', 'Greatest', 'Guardian', 'Guidance', 'Handling', 'Hardware', 'Headline', 'Heritage', 'Highland', 'Historic', 'Homeless', 'Homepage', 'Hospital', 'Humanity', 'Identify', 'Identity', 'Ideology', 'Imperial', 'Incident', 'Included', 'Increase', 'Indicate', 'Indirect', 'Industry', 'Informal', 'Informed', 'Inherent', 'Initiate', 'Innocent', 'Inspired', 'Instance', 'Integral', 'Intended', 'Interact', 'Interest', 'Interior', 'Internal', 'Internet', 'Interval', 'Intimate', 'Intranet', 'Invasion', 'Investor', 'Involved', 'Isolated', 'Judgment', 'Judicial', 'Junction', 'Keyboard', 'Landlord', 'Language', 'Laughter', 'Learning', 'Leverage', 'Lifetime', 'Lighting', 'Likewise', 'Limiting', 'Literary', 'Location', 'Magazine', 'Magnetic', 'Maintain', 'Majority', 'Marginal', 'Marriage', 'Material',
'Maturity', 'Maximize', 'Meantime', 'Measured', 'Medicine', 'Medieval', 'Memorial', 'Merchant', 'Midnight', 'Military', 'Minimize', 'Minister', 'Ministry', 'Minority', 'Mobility', 'Modeling', 'Moderate', 'Momentum', 'Monetary', 'Moreover', 'Mortgage', 'Mountain', 'Mounting', 'Movement', 'Multiple', 'Musician', 'National', 'Negative', 'Neighbor', 'Nineteen', 'Normally', 'Northern', 'Notebook', 'Numerous', 'Observer', 'Occasion', 'Offering', 'Official', 'Offshore', 'Operator', 'Opponent', 'Opposite', 'Optimism', 'Optional', 'Ordinary', 'Organize', 'Original', 'Overcome', 'Overhead', 'Overlook', 'Overseas', 'Overview', 'Painting', 'Parallel', 'Parental', 'Patented', 'Patience', 'Peaceful', 'Perceive', 'Periodic', 'Personal', 'Persuade', 'Petition', 'Physical', 'Pipeline', 'Planning', 'Platform', 'Pleasant', 'Pleasure', 'Politics', 'Portable', 'Portrait', 'Position', 'Positive', 'Possible', 'Possibly', 'Pounding', 'Powerful', 'Practice', 'Precious', 'Pregnant', 'Presence', 'Preserve', 'Pressing', 'Pressure', 'Previous', 'Princess', 'Printing', 'Priority', 'Prisoner', 'Probable', 'Probably', 'Producer', 'Profound', 'Progress', 'Properly', 'Property', 'Proposal', 'Proposed', 'Prospect', 'Protocol',
'Provided', 'Provider', 'Province', 'Publicly', 'Purchase', 'Pursuant', 'Quantity', 'Question', 'Rational', 'Reaction', 'Received', 'Receiver', 'Recently', 'Recovery', 'Regional', 'Register', 'Regulate', 'Relation', 'Relative', 'Relevant', 'Reliable', 'Reliance', 'Religion', 'Remember', 'Renowned', 'Repeated', 'Reporter', 'Republic', 'Required', 'Research', 'Resemble', 'Reserved', 'Resident', 'Resigned', 'Resource', 'Response', 'Restrict', 'Revision', 'Rigorous', 'Romantic', 'Sampling', 'Sanction', 'Scenario', 'Schedule', 'Scrutiny', 'Seasonal', 'Secondly', 'Security', 'Sensible', 'Sentence', 'Separate', 'Sequence', 'Sergeant', 'Shipping', 'Shooting', 'Shopping', 'Shortage', 'Shoulder', 'Simplify', 'Situated', 'Slightly', 'Software', 'Solution', 'Somebody', 'Somewhat', 'Southern', 'Speaking', 'Specific', 'Spectrum', 'Spending', 'Sporting', 'Standard', 'Standing', 'Standout', 'Sterling', 'Straight', 'Stranger', 'Strategy', 'Strength', 'Striking', 'Strongly', 'Struggle', 'Stunning', 'Suburban', 'Suddenly', 'Suitable', 'Superior', 'Supposed', 'Surgical', 'Surprise', 'Surround', 'Survival', 'Survivor', 'Sweeping', 'Swimming', 'Symbolic', 'Sympathy', 'Syndrome', 'Tactical', 'Tailored', 'Takeover',
'Tangible', 'Taxation', 'Taxpayer', 'Teaching', 'Teaspoon', 'Teenager', 'Tendency', 'Terminal', 'Terrible', 'Thinking', 'Thirteen', 'Thorough', 'Thousand', 'Threaten', 'Together', 'Tomorrow', 'Touching', 'Tracking', 'Training', 'Transfer', 'Traveled', 'Treasury', 'Triangle', 'Tropical', 'Turnover', 'Ultimate', 'Umbrella', 'Universe', 'Unlawful', 'Unlikely', 'Vacation', 'Valuable', 'Variable', 'Vertical', 'Victoria', 'Violence', 'Volatile', 'Warranty', 'Weakness', 'Weighted', 'Whatever', 'Whenever', 'Wherever', 'Wildlife', 'Wireless', 'Withdraw', 'Woodland', 'Workshop', 'Yourself'
]

words[4] = [
'Aardvarks', 'Abamperes', 'Abandoned', 'Abandonee', 'Abandoner', 'Babblings', 'Babelized', 'Babirusas', 'Cabaletta', 'Cabalisms', 'Cabalists', 'Caballero', 'Eagerness', 'Eaglewood', 'Ealdorman', 'Ealdormen', 'Earliness', 'Pacemaker', 'Pachyderm', 'Pachynema', 'Qalandars', 'Quadrants', 'Quadrated', 'Quadrates', 'Quadratic', 'Sabadilla', 'Sabbatize', 'Sablefish', 'Tabbouleh', 'Tabescent', 'Tablature', 'Tableland', 'Nagualism', 'Nahcolite', 'Vacancies', 'Vacations', 'Vaccinate', 'Vaccinees', 'Quizzical', 'Squizzing', 'Whizzbang', 'Jazziness', 'Showbizzy', 'Blackjack', 'Chazzanim', 'Chazzenim', 'Scuzzball', 'Pizzalike', 'Blizzardy', 'Embezzler', 'Schnozzle', 'Shockjock', 'Cheapjack', 'Equivoque', 'Jackknife', 'Mezzaluna', 'Paparazzi', 'Paparazzo', 'Pizzicati', 'Pizzicato', 'Shemozzle', 'Applejack', 'Fuzziness', 'Kibbutzim', 'Krummholz', 'Mezzanine', 'Muzziness', 'Podzolize', 'Pozzolana', 'Quickbeam', 'Smokejack', 'Amberjack', 'Blackbuck', 'Exchequer', 'Exoenzyme', 'Fizziness', 'Frizzante', 'Grandezza', 'Jackscrew', 'Jackstaff', 'Jacquerie', 'Maximizer', 'Mezzotint', 'Muckamuck', 'Quillback', 'Skyjacker', 'Backblock', 'Blackcock', 'Conjugacy', 'Coxcombry', 'Czarevich', 'Jacklight', 'Jargonize', 'Jiujutsus', 'Kabeljauw', 'Kickboxer', 'Liquidize', 'Outdazzle', 'Oxygenize', 'Pizzerias', 'Pompholyx', 'Poppycock', 
'Quicklime', 'Bedjacket', 'Bubblejet', 'Communize', 'Complexly', 'Crackback', 'Dizziness', 'Epoxidize', 'Equalizer', 'Huckaback', 'Hypoxemic', 'Jackfruit', 'Jacksmelt', 'Jayhawker', 'Joypopper', 'Juxtapose', 'Klezmorim', 'Machzorim', 'Objectify', 'Paycheque', 'Pickaback', 'Pipsqueak', 'Publicize', 'Quaffable', 'Quantizer', 'Quickfire', 'Quickstep', 'Quicktime', 'Quixotism', 'Schmaltzy', 'Superjock', 'Adjacency', 'Avizandum', 'Backbench', 'Bamboozle', 'Bijective', 'Blazingly', 'Bombazine', 'Cambozola', 'Carjacker', 'Chalutzim', 'Checkbook', 'Checkmark', 'Chibouque', 'Cockscomb', 'Diazotize', 'Exemplify', 'Exocyclic', 'Exoticize', 'Frequency', 'Hunchback', 'Jackstraw', 'Jaywalker', 'Jockstrap', 'Judgmatic', 'Junkerdom', 'Jurywoman', 'Jurywomen', 'Kibbitzer', 'Kinkajous', 'Mythicize', 'Objective', 'Outjockey', 'Packetize', 'Pepperbox', 'Piggyback', 'Pinchbeck', 'Polymyxin', 'Quartzite', 'Quartzose', 'Quicksand', 'Quillwork', 'Quiverful', 'Razorback', 'Victimize', 'Vulcanize', 'Zygomatic', 'Adjunctly', 'Affluenza', 'Alchemize', 'Amazingly', 'Apoenzyme', 'Balkanize', 'Blackwork', 'Blockwork', 'Bodycheck', 'Bouzoukia', 'Buckyball', 'Bumpkinly', 'Bushwhack', 'Chernozem', 'Chintzily', 'Chockfull', 'Clockwork', 'Cockamamy', 'Cockneyfy', 'Crowquill', 'Deoxidize', 'Enjoyably', 'Enzymatic', 'Equivocal', 'Euphemize', 'Executrix', 'Exequatur', 'Flambeaux', 'Izimbongi', 'Jambalaya', 'Jellyfish', 'Jellylike', 'Jewelfish', 'Jewellike', 'Jokesmith', 'Jubilance', 'Judgeship', 'Junkerism', 'Lampblack', 'Majuscule', 'Mechanize', 'Moonquake', 'Oxazolone', 'Oxyphilic', 
'Placekick', 'Proenzyme', 'Pulverize', 'Quadruply', 'Quebracho', 'Quickener', 'Quickness', 'Quintuply', 'Rhizobium', 'Sexualize', 'Slivovitz', 'Squawfish', 'Subclimax', 'Subjudice', 'Symbolize', 'Temazepam', 'Tzaddikim', 'Tzarevich', 'Volumizer', 'Wakizashi', 'Windowbox', 'Zeugmatic', 'Zoophilic', 'Zucchetto', 'Adjective', 'Adjutancy', 'Affixable', 'Affixment', 'Aquaponic', 'Backcrawl', 'Backtrack', 'Becquerel', 'Billycock', 'Blackbody', 'Blackface', 'Bodyclock', 'Breezeway', 'Brickwork', 'Brusquely', 'Buckbrush', 'Buckytube', 'Camelback', 'Capsulize', 'Catechize', 'Chabazite', 'Chaffinch', 'Chopsocky', 'Churchkey', 'Civilizer', 'Clozapine', 'Cockfight', 'Coequally', 'Conjugant', 'Convexity', 'Crookback', 'Cyberpunk', 'Dizygotic', 'Djellabah', 'Empathize', 'Emphasize', 'Equipment', 'Exceptive', 'Excusably', 'Exquisite', 'Fightback', 'Formulize', 'Frequence', 'Galvanize', 'Gauzelike', 'Gimmickry', 'Gogglebox', 'Haphazard', 'Hatchback', 'Humbucker', 'Hybridize', 'Hydrolyze', 'Hylozoism', 'Hypnotize', 'Hypoxemia', 'Immunizer', 'Injective', 'Jailbreak', 'Jellybean', 'Jocularly', 'Jocundity', 'Joyfuller', 'Jumpiness', 'Jumpsuits', 'Knockdown', 'Maximally', 'Mazaedium', 'Meclizine', 'Milkvetch', 'Mollymawk', 'Monocoque', 'Mujahedin', 'Mujahidin', 'Mummichog', 'Mycophagy', 'Myxoviral', 'Myxovirus', 'Obliquely', 'Photolyze', 'Pickthank', 'Piggybank', 'Piquantly', 'Plexiform', 'Prejudice', 'Punchbowl', 'Puppylike', 'Pyrolyzer', 'Quitclaim', 'Reoxidize', 'Schmoozer', 'Squabbler', 'Squeakily', 'Subjacent', 'Texturize', 'Trackback', 'Verbalize', 'Vocalizer', 
'Vulgarize', 'Woodchuck', 'Xylograph', 'Zestfully', 'Zirconium', 'Abjection', 'Acquiesce', 'Amazement', 'Amphioxus', 'Anglicize', 'Anonymize', 'Azimuthal', 'Backcloth', 'Backspace', 'Backstamp', 'Backswept', 'Backswing', 'Baldaquin', 'Barmbrack', 'Baroquely', 'Benchmark', 'Benchwork', 'Bijection', 'Blackball', 'Blackfish', 'Blackpoll', 'Blackwall', 'Blockship', 'Boutiquey', 'Breakbulk', 'Brushback', 'Bucketful', 'Buckhound', 'Buckwheat', 'Bulldozer', 'Byzantine', 'Carbazole', 'Carbonize', 'Carburize', 'Carcajous', 'Cataplexy', 'Cellblock', 'Chalazion', 'Chalkface', 'Champleve', 'Checkable', 'Chuckhole', 'Citizenly', 'Clinquant', 'Clocklike', 'Coachwhip', 'Coaxingly', 'Cocainize', 'Cognizant', 'Colchicum', 'Conjugate', 'Cookshack', 'Creampuff', 'Cubiculum', 'Currajong', 'Customize', 'Cymbidium', 'Dumptruck', 'Economize', 'Effluvium', 'Effluxion', 'Ejectable', 'Ejectment', 'Enjoyable', 'Enjoyment', 'Equitably', 'Euphonize', 'Excitably', 'Exclusive', 'Execrably', 'Exemplary', 'Exercycle', 'Expulsive', 'Fancywork', 'Flashback', 'Flippancy', 'Forejudge', 'Formalize', 'Freezable', 'Gallicize', 'Gazehound', 'Globalize', 'Gothicize', 'Harquebus', 'Heffalump', 'Hemolymph', 'Humanizer', 'Immovably', 'Impluvium', 'Influenza', 'Jerkwater', 'Jobholder', 'Jointworm', 'Joviality', 'Judiciary', 'Juicehead', 'Junctural', 'Juneberry', 'Juvenilia', 'Kavakavas', 'Kazillion', 'Kilohertz', 'Kilojoule', 'Kymograph', 'Lemmatize', 'Loquacity', 'Lorazepam', 'Maharajah', 'Majolicas', 'Majordomo', 'Mannequin', 'Marbleize', 'Marketize', 'Marmalize', 'Matchlock', 'Megahertz', 
'Megapixel', 'Metaxylem', 'Micronize', 'Minimizer', 'Mobilizer', 'Mockingly', 'Moneyback', 'Multiplex', 'Mumchance', 'Mycotoxin', 'Myxoedema', 'Namecheck', 'Notchback', 'Objection', 'Obliquity', 'Occupancy', 'Overcheck', 'Overglaze', 'Overprize', 'Packcloth', 'Palanquin', 'Panzootic', 'Paperback', 'Pappyshow', 'Passivize', 'Pauperize', 'Phenazine', 'Pickproof', 'Pidginize', 'Polyptych', 'Preconize', 'Prefrozen', 'Prejudger', 'Privatize', 'Puckishly', 'Pullquote', 'Pyroxenic', 'Pyroxylin', 'Quadruple', 'Quarryman', 'Quarrymen', 'Queenfish', 'Queenlike', 'Queenship', 'Quintuple', 'Rebbetzin', 'Rebbitzin', 'Rejective', 'Reliquefy', 'Requalify', 'Rhizotomy', 'Rubberize', 'Schnauzer', 'Schnitzel', 'Shadowbox', 'Shockwave', 'Squelcher', 'Subjugate', 'Subphylum', 'Summarize', 'Sweepback', 'Swingback', 'Syllabize', 'Technique', 'Thumbtack', 'Touchback', 'Trapezium', 'Unequally', 'Unfixable', 'Unmixable', 'Vandalize', 'Vaporizer', 'Vectorize', 'Wayzgoose', 'Weaponize', 'Whaleback', 'Wheelback', 'Womanizer', 'Workbench', 'Xenophobe', 'Xylophone', 'Zamindary', 'Zebrawood', 'Zemindary', 'Zinfandel', 'Zippiness', 'Zircalloy', 'Zookeeper', 'Zygospore', 'Accompany', 'Acquihire', 'Adjustive', 'Alkalizer', 'Aluminize', 'Amblyopic', 'Antiquark', 'Apologize', 'Appetizer', 'Aquaplane', 'Arabicize', 'Asphyxial', 'Babyccino', 'Backfield', 'Backlight', 'Backpedal', 'Backplane', 'Backshift', 'Bacterize', 'Bafflegab', 'Bajillion', 'Balthazar', 'Barbarize', 'Bazillion', 'Benzenoid', 'Benzidine', 'Bilharzia', 'Biohazard', 'Birchbark', 'Bizarrely', 'Blackbelt', 'Blackbird', 
'Blackbutt', 'Blackmail', 'Blackwood', 'Bombproof', 'Breakneck', 'Brummagem', 'Buckboard', 'Bullfinch', 'Bumbledom', 'Burlesque', 'Buxomness', 'Campcraft', 'Carryback', 'Catalyzer', 'Chaffweed', 'Chapstick', 'Chawbacon', 'Checkmate', 'Checkroom', 'Chipmaker', 'Chokingly', 'Chopstick', 'Churchman', 'Churchmen', 'Cicatrize', 'Citizenry', 'Clampdown', 'Clickable', 'Climbdown', 'Clubbable', 'Coachwork', 'Cocklebur', 'Cockroach', 'Colloquia', 'Columbium', 'Commodify', 'Compactly', 'Countback', 'Crackdown', 'Criticize', 'Crookneck', 'Cubbyhole', 'Cuckoldry', 'Currycomb', 'Cytotoxic', 'Diazonium', 'Diazotype', 'Disclimax', 'Dogmatize', 'Dominique', 'Duplexity', 'Eloquence', 'Epicyclic', 'Epimerize', 'Epitomize', 'Epizootic', 'Equifinal', 'Exchanger', 'Exculpate', 'Excursive', 'Excusable', 'Executive', 'Exophoric', 'Expansive', 'Expensive', 'Expletive', 'Explosive', 'Exponible', 'Exultancy', 'Factorize', 'Feudalize', 'Fluidizer', 'Flunkyism', 'Folkweave', 'Forecheck', 'Germanize', 'Gigahertz', 'Gigapixel', 'Glamorize', 'Gospelize', 'Gravadlax', 'Grazeable', 'Hammerkop', 'Harmonize', 'Hexachord', 'Hollyhock', 'Homoeobox', 'Hydrazide', 'Hydrazine', 'Hydrozoan', 'Hypomorph', 'Inequable', 'Isoenzyme', 'Izinyanga', 'Jarringly', 'Jeeringly', 'Jellyroll', 'Jestingly', 'Jitterbug', 'Joylessly', 'Judicious', 'Junketeer', 'Juridical', 'Kaolinize', 'Kerfuffle', 'Kickboard', 'Knobstick', 'Lebkuchen', 'Lexically', 'Magnetize', 'Mammiform', 'Marquetry', 'Matchbook', 'Mawkishly', 'Memorizer', 'Mercerize', 'Mesmerize', 'Methodize', 'Metricize', 'Muckraker', 'Multipack', 
'Mutualize', 'Nebulizer', 'Nonexempt', 'Nonfrozen', 'Noninjury', 'Numbskull', 'Nymphaeum', 'Objurgate', 'Optimizer', 'Overclock', 'Overgraze', 'Paganizer', 'Panjandra', 'Paralyzer', 'Parbuckle', 'Parquetry', 'Patchwork', 'Philippic', 'Phycology', 'Pikeperch', 'Pillarbox', 'Pitchfork', 'Pluralize', 'Pocketful', 'Poeticize', 'Polyphagy', 'Preoccupy', 'Projector', 'Prologize', 'Protozoic', 'Proximity', 'Punchball', 'Puppyhood', 'Quadrivia', 'Quillwort', 'Quodlibet', 'Rebaptize', 'Recognize', 'Reflexive', 'Rheumatiz', 'Rhizobial', 'Ruggedize', 'Saprozoic', 'Saxitoxin', 'Schmecker', 'Semimajor', 'Sequacity', 'Shamanize', 'Shipwreck', 'Sitzkrieg', 'Sleazebag', 'Slickrock', 'Smackdown', 'Squalidly', 'Squashily', 'Squeamish', 'Stockwhip', 'Sulfurize', 'Syllogize', 'Synopsize', 'Temporize', 'Throwback', 'Toxophily', 'Ubiquitin', 'Unkemptly', 'Unquietly', 'Vademecum', 'Vampishly', 'Vernalize', 'Veronique', 'Visualize', 'Wakefully', 'Whichaway', 'Whipstock', 'Womenfolk', 'Woodblock', 'Wreckfish', 'Xerophily', 'Zoophilia', 'Zoosporic', 'Accumbent', 'Acquittal', 'Actualize', 'Amphiboly', 'Animalize', 'Archduchy', 'Awkwardly', 'Backboard', 'Backcourt', 'Backdraft', 'Backplate', 'Backsight', 'Backsword', 'Bailiwick', 'Bakeapple', 'Banqueter', 'Banquette', 'Bellyflop', 'Bespeckle', 'Biaxially', 'Biconcave', 'Blackhead', 'Blackhole', 'Blackland', 'Blackspot', 'Blasphemy', 'Blockhead', 'Blockhole', 'Bookmaker', 'Bootblack', 'Brusquest', 'Brutalize', 'Buckthorn', 'Bumblebee', 'Cachectic', 'Cacophony', 'Camphoric', 'Casualize', 'Cavewoman', 'Cavewomen', 'Chalkhill', 
'Champagne', 'Champaign', 'Chanceful', 'Cheechako', 'Chemurgic', 'Chinkapin', 'Choplogic', 'Chromakey', 'Civically', 'Claviform', 'Clickbait', 'Climbable', 'Clingfilm', 'Clockwise', 'Coadjutor', 'Coaxially', 'Coccidium', 'Coccygeal', 'Colluvium', 'Communism', 'Concavely', 'Conqueror', 'Coulombic', 'Covalency', 'Cracksman', 'Cracksmen', 'Cryptonym', 'Cubically', 'Cybercafe', 'Cyclepath', 'Cyclicity', 'Cymophane', 'Dejection', 'Diabolize', 'Dumbfound', 'Dumbphone', 'Ejaculate', 'Equatable', 'Equimolar', 'Equisetum', 'Equitable', 'Exactable', 'Excavator', 'Excentric', 'Exception', 'Excessive', 'Excipient', 'Excisable', 'Exciseman', 'Excisemen', 'Excitable', 'Excitedly', 'Excitonic', 'Exclaimer', 'Excrement', 'Excretive', 'Execrable', 'Exemption', 'Exhalable', 'Expectant', 'Explicate', 'Fetishize', 'Filmmaker', 'Flaccidly', 'Flammable', 'Flappable', 'Flashbulb', 'Flexitime', 'Fluxional', 'Foppishly', 'Foxhunter', 'Frenchify', 'Gangplank', 'Gawkishly', 'Gazillion', 'Geologize', 'Glycaemic', 'Goldbrick', 'Gorgonize', 'Graywacke', 'Greywacke', 'Gunnysack', 'Gutbucket', 'Hackberry', 'Harlequin', 'Hawkishly', 'Hawksbill', 'Hellenize', 'Helpfully', 'Hemicycle', 'Hexaploid', 'Hillclimb', 'Homonymic', 'Honeycomb', 'Hylozoist', 'Hypercube', 'Hypergamy', 'Hypericum', 'Hypertext', 'Hypomanic', 'Imidazole', 'Immixture', 'Immovable', 'Impactful', 'Inexactly', 'Injectant', 'Injection', 'Injustice', 'Ionizable', 'Jaborandi', 'Jacaranda', 'Jargonish', 'Jealously', 'Jointedly', 'Joliotium', 'Jollytail', 'Joyridden', 'Juiceless', 'Juiciness', 'Kanamycin', 'Kilocycle', 
'Kingmaker', 'Knavishly', 'Knowingly', 'Krummhorn', 'Labialize', 'Lacquerer', 'Lespedeza', 'Liquidity', 'Localizer', 'Lymphatic', 'Lyophobic', 'Mammalogy', 'Mammogram', 'Manzanita', 'Maquisard', 'Marijuana', 'Martyrize', 'Matchplay', 'Maxillary', 'Megacycle', 'Metallize', 'Metroplex', 'Microchip', 'Microcopy', 'Midweekly', 'Midwicket', 'Milkshake', 'Misadjust', 'Mispickel', 'Mobocracy', 'Modernize', 'Monkeypod', 'Monophyly', 'Monzonite', 'Morphemic', 'Mullygrub', 'Multisize', 'Mycophile', 'Mythmaker', 'Neckcloth', 'Nighthawk', 'Noncyclic', 'Nonliquid', 'Nonunique', 'Normalize', 'Numbingly', 'Occupance', 'Overexact', 'Oxycodone', 'Packboard', 'Palletize', 'Paranymph', 'Pelletize', 'Perilymph', 'Peroxidic', 'Phenocopy', 'Phenoxide', 'Photobomb', 'Pickpurse', 'Picnicker', 'Plaquette', 'Plastique', 'Platinize', 'Playfully', 'Podzolise', 'Pokerwork', 'Polygamic', 'Polymorph', 'Polyphony', 'Polytypic', 'Polyvinyl', 'Psalmbook', 'Psychical', 'Punchcard', 'Pushfully', 'Pycnidium', 'Pyridoxal', 'Pyromancy', 'Quercetin', 'Querencia', 'Quiescent', 'Quittance', 'Quotative', 'Randomize', 'Razorbill', 'Razorfish', 'Reconquer', 'Relacquer', 'Saltchuck', 'Schnecken', 'Scrubfowl', 'Sequencer', 'Sexcapade', 'Sforzandi', 'Sforzando', 'Shaykhdom', 'Shellback', 'Signalbox', 'Sixtyfold', 'Sizarship', 'Skiamachy', 'Skippable', 'Slaphappy', 'Slingback', 'Smorzando', 'Solemnize', 'Soliloquy', 'Spacewalk', 'Sparkplug', 'Speedbump', 'Spondulix', 'Squamosal', 'Squiredom', 'Stickwork', 'Stinkbomb', 'Subsidize', 'Subtilize', 'Symphonic', 'Symphylan', 'Systemize', 'Tagmatize', 
'Tamoxifen', 'Taxonomic', 'Tchotchke', 'Textspeak', 'Thematize', 'Therapize', 'Thingummy', 'Toxically', 'Tumblebug', 'Unbeknown', 'Unluckily', 'Verbascum', 'Viewgraph', 'Vizierial', 'Waterbuck', 'Whichever', 'Wimpishly', 'Wobbegong', 'Workmanly', 'Workplace', 'Workwoman', 'Workwomen', 'Xenophile', 'Xerograph', 'Xerophyte', 'Zamindari', 'Zealously', 'Zeitgeber', 'Zemindari', 'Zettabyte', 'Zillionth', 'Acceptive', 'Acclivity', 'Acquitter', 'Acyclovir', 'Affective', 'Alicyclic', 'Amazonite', 'Analogize', 'Anatomize', 'Annualize', 'Anthozoan', 'Antiknock', 'Antiquary', 'Antiquity', 'Apocrypha', 'Aquilegia', 'Arabesque', 'Auxotroph', 'Axiomatic', 'Babyishly', 'Bacchanal', 'Backbiter', 'Backcross', 'Backhouse', 'Backrower', 'Backslash', 'Backwater', 'Barkcloth', 'Bashfully', 'Beachball', 'Beatboxer', 'Biblicism', 'Blacklead', 'Bleomycin', 'Bloodbank', 'Bobweight', 'Bombshell', 'Bombsight', 'Bookshelf', 'Booziness', 'Boxercise', 'Brickyard', 'Briquette', 'Brushwork', 'Buckteeth', 'Bucktooth', 'Bulgingly', 'Bullfight', 'Byproduct', 'Cacodylic', 'Calcifuge', 'Cartelize', 'Catchpoll', 'Cauterize', 'Champerty', 'Changeful', 'Chauffeur', 'Checkless', 'Checklist', 'Checkrein', 'Cheekbone', 'Chickadee', 'Chiefship', 'Chivalric', 'Chokehold', 'Chowhound', 'Chowkidar', 'Chronaxie', 'Clerkship', 'Climactic', 'Clownfish', 'Cocksfoot', 'Cofferdam', 'Combative', 'Commencer', 'Commingle', 'Community', 'Complicit', 'Concavity'    
]

words[5] = [
'Alchemized', 'Amberjacks', 'Apoenzymes', 'Applejacks', 'Appreciate', 'Aquaphobes', 'Aquaphobia', 'Aquaphobic', 'Asexualize', 'Autoxidize', 'Axiomatize', 'Azobenzene', 'Backchecks', 'Backpacked', 'Backpacker', 'Balkanized', 'Bamboozled', 'Bedazzling', 'Bedjackets', 'Bhikkhunis', 'Blackbucks', 'Blackcocks', 'Blackjacks', 'Blitzkrieg', 'Blizzarded', 'Blizzardly', 'Bodychecks', 'Bolshevize', 'Buckjumped', 'Buckjumper', 'Bumfreezer', 'Bumfuzzled', 'Bumfuzzles', 'Buzzworthy', 'Carboxylic', 'Carjacking', 'Catechizer', 'Catechizes', 'Chabazites', 'Chaptalize', 'Checkboxes', 'Checkmarks', 'Chequebook', 'Chernozems', 'Chickenpox', 'Chiffchaff', 'Chimpanzee', 'Chinquapin', 'Chromizing', 'Chymifying', 'Cinchonize', 'Circumflex', 'Cognizably', 'Colloquize', 'Communized', 'Complexify', 'Complexity', 'Crackajack', 'Crazyweeds', 'Cyclohexyl', 'Dazzlement', 'Dazzlingly', 'Deoxidized', 'Deoxidizer', 'Deoxidizes', 'Diazotized', 'Diazotizes', 'Dizzyingly', 'Doxography', 'Effeminize', 'Embezzlers', 'Embezzling', 'Empathized', 'Emphasized', 'Enzymology', 'Epoxidized', 'Epoxidizes', 'Equalizers', 'Equalizing', 'Equivoques', 'Euphemized', 'Everything', 'Exahertzes', 'Exchequers', 'Exorcizing', 'Exoticized', 'Exoticizes', 'Expertized', 'Fetichized', 'Fetichizes', 'Friendship', 'Frizzliest', 'Gadzookery', 'Grizzliest', 'Hokeypokey', 'Holoenzyme', 'Homozygote', 'Homozygous', 'Hybridized', 'Hybridizer', 'Hybridizes', 'Hydrazides', 'Hydroxylic', 'Hyphenized', 'Hyphenizes', 'Hypnotized', 'Hypnotizer', 'Hypnotizes', 'Hypoxaemia', 'Hypoxemias', 'Intermezzi', 'Intermezzo', 
'Jabberwock', 'Jackhammer', 'Jacklights', 'Jackrabbit', 'Jackscrews', 'Jackshafts', 'Jackstaffs', 'Jacqueries', 'Japanizing', 'Jargonized', 'Jargonizes', 'Jayhawkers', 'Jaywalkers', 'Jaywalking', 'Jeopardize', 'Jockeyship', 'Johnnycake', 'Joypopping', 'Jumboizing', 'Juvenilize', 'Juxtaposed', 'Karyolymph', 'Kazatskies', 'Kibbitzing', 'Kibbutznik', 'Kickboxers', 'Kickboxing', 'Knickknack', 'Knockbacks', 'Kolkhoznik', 'Lexicalize', 'Liquidized', 'Liquidizer', 'Liquidizes', 'Lumberjack', 'Lyophilize', 'Maximizing', 'Mechanized', 'Mezzalunas', 'Mezzanines', 'Mezzotints', 'Microquake', 'Mizzenmast', 'Morbidezza', 'Motivation', 'Mozzarella', 'Mycorrhiza', 'Mythicized', 'Mythicizer', 'Mythicizes', 'Myxoedemic', 'Myxomycete', 'Nephropexy', 'Outdazzled', 'Outdazzles', 'Oxidizable', 'Oxycephaly', 'Oxygenized', 'Oxygenizer', 'Oxygenizes', 'Packetized', 'Packetizes', 'Paddywhack', 'Passamezzo', 'Paycheques', 'Photolyzed', 'Photolyzes', 'Phyllotaxy', 'Phytophagy', 'Phytotoxic', 'Pipsqueaks', 'Pizzicatos', 'Podzolized', 'Podzolizes', 'Polygamize', 'Polymyxins', 'Pozzolanas', 'Pozzolanic', 'Prequalify', 'Puzzledoms', 'Puzzlement', 'Puzzlingly', 'Pyrolyzing', 'Quadplexes', 'Quadraplex', 'Quadratrix', 'Quadruplex', 'Quantizers', 'Quantizing', 'Quartzites', 'Quatorzain', 'Quickbeams', 'Quicklimes', 'Quicksteps', 'Quillbacks', 'Quinaquina', 'Quincunxes', 'Quixotical', 'Quizmaster', 'Razorbacks', 'Rejuvenize', 'Rhizomorph', 'Rhizophore', 'Rhythmized', 'Rhythmizes', 'Schemozzle', 'Schizocarp', 'Schizogony', 'Schizopods', 'Schizziest', 'Schmoozing', 'Schnozzles',
'Schvitzing', 'Scuzzballs', 'Sexualized', 'Shemozzled', 'Shemozzles', 'Showjumper', 'Sjambokked', 'Skyjackers', 'Skyjacking', 'Snazziness', 'Squeezable', 'Squeezebox', 'Squeeziest', 'Squirarchy', 'Strawberry', 'Subjectify', 'Supplejack', 'Symbolized', 'Symptomize', 'Synonymize', 'Syphilized', 'Syphilizes', 'Tetrazzini', 'Texturized', 'Trihydroxy', 'Undazzling', 'Unmuzzling', 'Unoxidized', 'Unpuzzling', 'Vampirized', 'Victimized', 'Viziership', 'Vizirships', 'Whizzbangs', 'Whizzingly', 'Xanthophyl', 'Xerophytic', 'Xiphopagic', 'Xylophonic', 'Youthquake', 'Zeaxanthin', 'Zigzaggers', 'Zigzaggery', 'Zigzagging', 'Zincifying', 'Zombifying', 'Zoomorphic', 'Zygobranch', 'Zygodactyl', 'Zygomorphy', 'Zygomycete', 'Zygophytes'
]


log = False
hard = input("Hard mode (Y/N): ")
if hard.lower() == "y":
    n = 6
elif hard.lower() == "log hard":
    n = 6
    log = True
elif hard.lower().replace(" ","") == "log":
    n = 5
    log = True
elif hard.lower() == "log easy":
    n = 4
    log = True
else:
    easy = input("Easy mode (Y/N): ")
    if easy.lower() == "y":
        n = 4
    else:
        n = 5

jvalue = 2**(n-1)

register = []
for i in range(len(words)):
    for j in range(jvalue):
        index = int(random.random()*len(words[i]))
        register.append(f"{words[i][index]} ")
    jvalue = int(jvalue//2)
parra = "".join(register)

if log:
    devlog()
    quit()

newline()
start = input("Enter anything to start.")
del(start)

correct_words = 0
tic = time.time()
i, user_input = 0, []
for word in register:
    i += 1
    word = word.replace(" ","")
    print(f"WORD({i}/{len(register)})): {word.upper()}")
    inp = input(">>> ")

    if inp.lower() == word.lower():
        correct_words += 1
    user_input.append(inp)
    toc = time.time()
    timem = (toc - tic)/60
    print(f"\nSpeed: {int(correct_words/timem)} words/min @{toc-tic}s.")

toc = time.time()
timem = (toc - tic)/60
newline()

charv = 0
for inp in user_input:
    charv += len(inp)

print(f"Total Time: {timem*60}s.")
print(f"Net Typing speed: {int(correct_words/timem)} words/min.")
print(f"Gross Typing speed: {int(len(register)/timem)} words/min.")
print(f"Net Accuracy: {(correct_words/len(register))*100}% of words.\n")
print(f"Characters per minute: {int(charv/timem)} cpm.")
print(f"Approx. Typing speed: {int(charv/(5*timem))} words/min.")

newline()
